CREATE TABLE IF NOT EXISTS users (telegram_id BIGINT PRIMARY KEY, username TEXT, first_name TEXT, joined_at TIMESTAMPTZ NOT NULL, last_seen TIMESTAMPTZ NOT NULL, articles_read INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS requests (id BIGSERIAL PRIMARY KEY, telegram_id BIGINT, url TEXT, domain TEXT, title TEXT, success BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS errors (id BIGSERIAL PRIMARY KEY, telegram_id BIGINT, url TEXT, error TEXT, created_at TIMESTAMPTZ NOT NULL);
